# Generated by Django 5.0 on 2024-05-17 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('github_repo', models.CharField(max_length=500)),
                ('primary_programming_language', models.CharField(max_length=500)),
                ('slug', models.SlugField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coderoom', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
