# Generated by Django 5.0 on 2024-05-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderoom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderoom',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
