# Generated by Django 5.0 on 2024-05-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_personsss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Personsss',
        ),
    ]
